version: '3.8'
services:
  web:
    build: .
    container_name: contacts_app
    command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker app.main:app --reload --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: contacts_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=a1k8u2
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data:
